<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\UserController;
use Illuminate\Auth\Events\Authenticated;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    // Checkout routes
    Route::post('/booking-detail/{room}', [RoomController::class, 'checkout']);
    Route::post('/place-order/{room}', [RoomController::class, 'placeOrder']);
});
require __DIR__ . '/auth.php';

// This route redirects the uesr from default login page generated by FILAMENT to another page the developer chooses it
Route::get('/admin/login', function () {
    return redirect()->to('/login');
})->name('filament.admin.auth.login');

Route::get('/logout', [AuthenticatedSessionController::class, 'destroy']);
Route::get('/dashboard', [UserController::class, 'dashboardRedirect']);




// View Pages routes
Route::get('/', [HomeController::class, 'index'])->name('homepage');
Route::get('/room-details/{room}', [RoomController::class, 'ShowRoomDetails']);
Route::get('/about', [HomeController::class, 'ShowAbout']);
Route::get('/all-room', [HomeController::class, 'ShowAllRoom']);
Route::get('/contact', [HomeController::class, 'ShowContact']);
Route::get('/buildings', [HomeController::class, 'ShowBuildings']);
Route::get('/buildings/{building}/rooms', [HomeController::class, 'ShowBuildingRooms']);
